name: release
on:
  push:
    branches:
      - master

jobs:
  build:
    uses: homebots/workflows/.github/workflows/node-build-release.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
